export enum ACTION_TYPES {
    CREATE_NEW_USER = "CREATE_NEW_USER",
    UPDATE_EXISTING_USER = "UPDATE_EXISTING_USER",
    DELETE_EXISTING_USER = "DELETE_EXISTING_USER",
    LOG_USER = "LOG_USER",
    LOGOUT_USER = "LOGOUT_USER",
    TEST_ASYNC = "TEST_ASYNC",
    TEST = "TEST"
} 